# Generated by Django 3.0.4 on 2020-07-09 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allprojecct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=20)),
                ('project_desc', models.TextField(max_length=1000)),
                ('project_url', models.URLField(blank=True, null=True)),
                ('project_tech', models.TextField(max_length=500)),
            ],
        ),
    ]
