# Generated by Django 3.0.4 on 2020-07-08 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=250)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True)),
            ],
        ),
    ]
