# Generated by Django 3.0.4 on 2020-08-04 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='position',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='skills',
            name='tools',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
